# Generated by Django 4.2 on 2023-07-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_details',
            fields=[
                ('course_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_discription', models.TextField()),
                ('lectures_list', models.TextField()),
                ('course_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('student_id', models.CharField(max_length=45, null=True)),
                ('password', models.CharField(max_length=45, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.courses_details')),
            ],
        ),
    ]
