# Generated by Django 4.2 on 2023-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_program_student_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='re_enter_email',
        ),
        migrations.AddField(
            model_name='student',
            name='re_password',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
