# Generated by Django 4.2 on 2023-07-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_re_enter_email_student_re_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
